#!/bin/bash

# Setup certificates
cd $TRAVIS_BUILD_DIR/travis/certs/testca

openssl req -x509 -config openssl.cnf -newkey rsa:2048 -days 365 \
    -out cacert.pem -outform PEM -subj /CN=MyTestCA/ -nodes

openssl x509 -in cacert.pem -out cacert.cer -outform DER

cd ../server

openssl genrsa -out key.pem 2048

openssl req -new -key key.pem -out req.pem -outform PEM \
    -subj /CN=$(hostname)/O=server/ -nodes

cd ../testca

openssl ca -config openssl.cnf -in ../server/req.pem -out \
    ../server/cert.pem -notext -batch -extensions server_ca_extensions

cd ../server

openssl pkcs12 -export -out keycert.p12 -in cert.pem -inkey key.pem \
    -passout pass:net-rabbitmq

# Start RabbitMQ server in background
RABBITMQ_PID_FILE="$TRAVIS_BUILD_DIR/rabbitmq.pid" \
RABBITMQ_CONFIG_FILE="$TRAVIS_BUILD_DIR/travis/rabbitmq.conf" \
$TRAVIS_BUILD_DIR/rabbitmq_server-$RABBITMQ_VERSION/sbin/rabbitmq-server &

# Ensure the server is running
$TRAVIS_BUILD_DIR/rabbitmq_server-$RABBITMQ_VERSION/sbin/rabbitmqctl wait $TRAVIS_BUILD_DIR/rabbitmq.pid

# Poll server for status
$TRAVIS_BUILD_DIR/rabbitmq_server-$RABBITMQ_VERSION/sbin/rabbitmqctl status

# Enable the management tool used by some tests
$TRAVIS_BUILD_DIR/rabbitmq_server-$RABBITMQ_VERSION/sbin/rabbitmq-plugins enable rabbitmq_management
